[[redirects]]
  from = "https://*"
  to = "https://netlify.app"
  status = 301
  force = true
  conditions = {Role = []} # Membantu Netlify memisahkan domain utama

# Aturan khusus jika ada yang mengakses lewat HTTP biasa (bukan HTTPS)
[[redirects]]
  from = "http://*"
  to = "https://netlify.app"
  status = 301
  force = true
