packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@sanity/diff@6.7.0 || 6.13.1'
  - '@sanity/mutator@6.7.0 || 6.13.1'
  - '@sanity/schema@6.7.0 || 6.13.1'
  - '@sanity/types@6.7.0 || 6.13.1'
  - '@sanity/util@6.7.0 || 6.13.1'
  - '@sanity/vision@6.7.0 || 6.13.1'
  - sanity@6.7.0 || 6.13.1
  - '@rolldown/binding-openharmony-arm64@1.2.8'
  - '@sanity/access-ui@6.13.1'
  - '@sanity/validation@6.13.1'
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - esbuild
